dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: lint
      script:
        - ng lint
#    - stage: test
 #     script:
 #       - npm run test:lib-coverage
 #       - npm run report-coverage:lib
    - stage: update version
      script:
        - npm version minor -m "Upgrade to %s [skip ci]" --force
    - stage: build & publish showcase
      script:
        - npm run build:showcase
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/angularanimatedcounter
      if: branch = release
      on:
        branch: release
    - stage: build & publish lib
      script:
        - npm run build:lib
      if: branch = release
