language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
    - release
before_script:
  - npm install
script:
  - npm version minor -m "Upgrade to %s [skip ci]" --force
  - ng lint
  - ng build --prod --base-href https://vanishdark.github.io/angularanimatedcounter/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  local_dir: dist/y
  on:
    branch: page
